In [5]:
# 各鄉鎮市區人口密度.csv
url = 'https://sheethub.com/data.gov.tw/%E5%90%84%E9%84%89%E9%8E%AE%E5%B8%82%E5%8D%80%E4%BA%BA%E5%8F%A3%E5%AF%86%E5%BA%A6?format=csv'

import pandas as pd

frame1 = pd.read_csv(url)
display(frame1.head(n=10))

   統計年     區域別   年底人口數     土地面積   人口密度
0  102  臺南市將軍區   20808  41.9796    496
1  102  高雄市新興區   53170   1.9764  26902
2  102  高雄市前金區   28038   1.8573  15096
3  102  高雄市苓雅區  177716   8.1522  21800
4  102  高雄市前鎮區  194835  19.1207  10190
5  102  高雄市旗津區   29040   1.4639  19837
6  102  高雄市小港區  156115  41.2061   3789
7  102  高雄市鳳山區  352574  26.7590  13176
8  102  高雄市林園區   70436  32.2860   2182
9  102  高雄市大寮區  110449  71.0400   1555

In [9]:
frame1.index = frame1['區域別']
frame1.head()

        統計年     區域別   年底人口數     土地面積   人口密度
區域別
臺南市將軍區  102  臺南市將軍區   20808  41.9796    496
高雄市新興區  102  高雄市新興區   53170   1.9764  26902
高雄市前金區  102  高雄市前金區   28038   1.8573  15096
高雄市苓雅區  102  高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  102  高雄市前鎮區  194835  19.1207  10190

In [11]:
frame2 = frame1[ ['年底人口數', '土地面積', '人口密度'] ]
frame2.head()

         年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190

In [13]:
errDf = frame2[frame2['年底人口數'] == '…']
display(errDf)

display(errDf.index)

errList = list(errDf.index)
display(errList)

frame3 = frame2.drop(index=errList)

     年底人口數    土地面積 人口密度
區域別
東沙群島     …  2.3800    …
南沙群島     …  0.4896    …

Index(['東沙群島', '南沙群島'], dtype='object', name='區域別')

['東沙群島', '南沙群島']

In [14]:
# 將 字串 轉成 數字
frame3['年底人口數'] = frame3['年底人口數'].astype(int)
frame3['土地面積'] = frame3['土地面積'].astype(float)
frame3['人口密度'] = frame3['人口密度'].astype(int)

frame3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 368 entries, 臺南市將軍區 to 新北市新莊區
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   368 non-null    int32
 1   土地面積    368 non-null    float64
 2   人口密度    368 non-null    int32
dtypes: float64(1), int32(2)
memory usage: 8.6+ KB

In [17]:
frame3.head(n=10)

         年底人口數     土地面積   人口密度
區域別
臺南市將軍區   20808  41.9796    496
高雄市新興區   53170   1.9764  26902
高雄市前金區   28038   1.8573  15096
高雄市苓雅區  177716   8.1522  21800
高雄市前鎮區  194835  19.1207  10190
高雄市旗津區   29040   1.4639  19837
高雄市小港區  156115  41.2061   3789
高雄市鳳山區  352574  26.7590  13176
高雄市林園區   70436  32.2860   2182
高雄市大寮區  110449  71.0400   1555