In [12]:
import pandas as pd

def less60(v, prop=''):
    return prop if v < 60 else None

df = pd.read_csv('學生成績.csv')

df.style.map(less60, prop='color:red;', subset=['國文', '數學']) \
        .format(precision=2, subset=['平均'])